version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: payment-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_eventstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  localstack:
    image: localstack/localstack
    container_name: payment-localstack
    ports:
      - "4566:4566"            
    environment:
      - SERVICES=sqs,sns       
      - DEFAULT_REGION=sa-east-1
      - DEBUG=1
    volumes:
      - "./localstack_init:/etc/localstack/init/ready.d"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: payment-elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false" 
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: payment-kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200" 
    depends_on:
      - elasticsearch
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: payment-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
 
volumes:
  esdata:
  pgdata: