version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: payment-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_eventstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  localstack:
    image: localstack/localstack
    container_name: payment-localstack
    ports:
      - "4566:4566"            
    environment:
      - SERVICES=sqs,sns       
      - DEFAULT_REGION=sa-east-1
      - DEBUG=1
    volumes:
      - "./localstack_init:/etc/localstack/init/ready.d"
      - "./localstack_init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: payment-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
  loki:
    image: grafana/loki:2.9.2
    container_name: payment-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: payment-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
 
volumes:
  pgdata: