apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-exporter
  namespace: tech-challenge-payment
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:latest
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_URI 
          valueFrom:
            secretKeyRef:
              name: payment-api-secrets
              key: PostgresExporter__Connection
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"