apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secrets
  namespace: tech-challenge-payment
type: Opaque
stringData:
  # Database Configuration (External RDS)
  ConnectionStrings__DefaultConnection: "Host=payment-service-db.clgce4qew71m.sa-east-1.rds.amazonaws.com;Port=5432;Database=postgres;Username=postgres;Password=lXfqHg3OMMm1IePIKK22"
  
  # JWT Configuration
  Jwt__Key: "keydeteste1234565"
