apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secrets
  namespace: tech-challenge-payment
type: Opaque
stringData:
  # Database Configuration (External RDS)
  ConnectionStrings__DefaultConnection: "Host=payment-postgres-db.clgce4qew71m.sa-east-1.rds.amazonaws.com;Port=5432;Database=payment_eventstore;Username=postgres;Password=u9n1K6QZO|Ny"
  PostgresExporter__Connection: "postgres://postgres:u9n1K6QZO|Ny@payment-postgres-db.clgce4qew71m.sa-east-1.rds.amazonaws.com:5432/payment_eventstore?sslmode=require"
  # JWT Configuration
  Jwt__Key: "keydeteste1234565"
  