apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api-sa
  namespace: tech-challenge-payment
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::208452488125:role/PaymentServiceRole"