AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PaymentService.Processor
  Processa comandos de pagamento recebidos via SQS para os contextos de Wallet e Purchase.

Parameters:
  RdsHost:
    Type: String
    Description: O endpoint do banco de dados RDS.
  RdsPassword:
    Type: String
    Description: A senha do banco de dados RDS.
    NoEcho: true 
  SnsTopicArn:
    Type: String
    Description: O ARN do tópico SNS para publicar eventos.
  ReplyQueueName:
    Type: String
    Description: O nome da fila SQS para respostas RPC.
  ElasticUrl:
    Type: String
    Description: URL do cluster Elasticsearch.
  ElasticId: 
    Type: String
    Description: O ID da API Key do Elasticsearch.
    NoEcho: true
  ElasticApiKey:
    Type: String
    Description: Chave de API do Elasticsearch.
    NoEcho: true

Globals:
  Function:
    Timeout: 30 
    MemorySize: 512 

Resources:
  WalletDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: wallet-queue-dlq

  WalletQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: wallet-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WalletDLQ.Arn
        maxReceiveCount: 3

  PurchaseDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: purchase-queue-dlq

  PurchaseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: purchase-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PurchaseDLQ.Arn
        maxReceiveCount: 3
  PaymentProcessorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: PaymentService.Processor::PaymentService.Processor.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./  

      Events:
        WalletQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt WalletQueue.Arn
            BatchSize: 10 
            Enabled: true

        PurchaseQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt PurchaseQueue.Arn
            BatchSize: 10
            Enabled: true
      
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt WalletQueue.QueueName
        - SQSPollerPolicy:
            QueueName: !GetAtt PurchaseQueue.QueueName
            
        - SNSPublishMessagePolicy:
            TopicName: payment-topic 

        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "sqs:SendMessage"
                - "sqs:GetQueueUrl"
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ReplyQueueName}"
         
        - VPCAccessPolicy: {}
  
      Environment:
        Variables:
          ConnectionStrings__DefaultConnection: !Sub "Host=${RdsHost};Port=5432;Database=postgres;Username=postgres;Password=${RdsPassword}"
          AWS__Region: "sa-east-1"
          AWS__SnsTopicArn: !Ref SnsTopicArn
          AWS__WalletCommandQueueUrl: !Ref WalletQueue
          AWS__PurchaseCommandQueueUrl: !Ref PurchaseQueue
          AWS__ReplyQueueName: !Ref ReplyQueueName


          Serilog__Using__0: "Serilog.Sinks.Console"
          Serilog__Using__1: "Serilog.Sinks.Elasticsearch"
          Serilog__Using__2: "Serilog.Enrichers.Environment"
          Serilog__Using__3: "Serilog.Enrichers.Thread"
          
          Serilog__MinimumLevel__Default: "Information"
          Serilog__MinimumLevel__Override__Microsoft: "Warning"

          Serilog__WriteTo__0__Name: "Console"
          Serilog__WriteTo__1__Name: "Elasticsearch"
          Serilog__WriteTo__1__Args__nodeUris: !Ref ElasticUrl
          Serilog__WriteTo__1__Args__indexFormat: "paymentservice-logs-{0:yyyy.MM.dd}"
          Serilog__WriteTo__1__Args__autoRegisterTemplate: "true"
          Serilog__WriteTo__1__Args__apiKey: !Ref ElasticApiKey

          Elasticsearch__Uri: !Ref ElasticUrl # Parâmetro do template
          Elasticsearch__Id: !Ref ElasticId # Parâmetro do template
          Elasticsearch__ApiKey: !Ref ElasticApiKey # Parâmetro do template
          APPLICATION_NAME: "PaymentService.Processor" # Nome estático da aplicação

          Serilog__Enrich__0: "FromLogContext"
          Serilog__Enrich__1: "WithMachineName"
          Serilog__Enrich__2: "WithThreadId"
